language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "code2bits-github"
    token: $SONAR_TOKEN
script:
  - sonar-scanner
  - mvn clean install
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
